// Carino Fiscal — offline cache.
//
// Offline is the premise, not an enhancement: a counter in a basement with no
// signal is exactly where this app has to work. So the whole site is
// precached on install, and every fetch is served cache-first.
//
// Cache-first is safe here because the app makes no network requests of its own
// once loaded — there is no live data to go stale. The only thing that changes
// is the app itself, and VERSION is a hash of the shipped bytes, so a new build
// gets a new cache without anybody having to remember to say so.
//
// The lists below are derived from the repo by tools/build_sw.py. Editing them
// by hand is how a file comes to be shipped but not cached, which is the one
// failure this app cannot afford; run the script instead. tools/validate.py
// runs the same code as a check and fails the build on a block that has
// drifted, because three rounds of asking people to remember produced three
// stale blocks.
//
// The lists are still not the last word: see declared() for the shipped files
// the app itself treats as authoritative about what exists, which the worker
// reads at install time and precaches regardless of what the script last saw.
// What that cannot repair is VERSION, because a stale one means sw.js's own
// bytes never change and no browser ever reinstalls it — which is why the gate
// matters. Nothing declared is ever counted as cached: readiness is measured
// against the cache itself, in offlineStatus().

// --- begin generated by tools/build_sw.py ---
const VERSION = 'carino-fiscal-ebaa72b7edfc';

// Everything the app cannot start without, fetched all-or-nothing: a
// half-installed shell is worse than no shell, because it looks like one.
const SHELL = [
    './',
    'apple-touch-icon.png',
    'carino-bridge.js',
    'carino-clock.js',
    'carino-lang.js',
    'carino-navbar.js',
    'demo.json',
    'fonts/carino-fonts.css',
    'i18n.js',
    'icon-192.png',
    'icon-512-maskable.png',
    'icon-512.png',
    'index.html',
    'js/app.js',
    'js/engines.js',
    'js/import.js',
    'js/phonetic.js',
    'js/share.js',
    'js/store.js',
    'logo.webp',
    'manifest.webmanifest',
    'registry/ar.json',
    'registry/au.json',
    'registry/be.json',
    'registry/br.json',
    'registry/ca.json',
    'registry/cl.json',
    'registry/co.json',
    'registry/de.json',
    'registry/es.json',
    'registry/fr.json',
    'registry/gb.json',
    'registry/gr.json',
    'registry/in.json',
    'registry/index.json',
    'registry/it.json',
    'registry/jp.json',
    'registry/mx.json',
    'registry/nl.json',
    'registry/pe.json',
    'registry/pl.json',
    'registry/pt.json',
    'registry/us.json',
    'registry/za.json',
    'vendor/qrcode-generator-1.4.4.js',
];

// Cached in a second, failure-tolerant pass, and still required before the
// app will call itself offline ready.
const BULK = [
    'fonts/IBMPlexMono-400-cyrillic.woff2',
    'fonts/IBMPlexMono-400-latin-ext.woff2',
    'fonts/IBMPlexMono-400-latin.woff2',
    'fonts/IBMPlexMono-600-cyrillic.woff2',
    'fonts/IBMPlexMono-600-latin-ext.woff2',
    'fonts/IBMPlexMono-600-latin.woff2',
    'fonts/IBMPlexMono-700-cyrillic.woff2',
    'fonts/IBMPlexMono-700-latin-ext.woff2',
    'fonts/IBMPlexMono-700-latin.woff2',
    'fonts/IBMPlexSans-400-latin.woff2',
    'fonts/IBMPlexSans-600-latin.woff2',
    'fonts/IBMPlexSans-700-latin.woff2',
    'fonts/IBMPlexSans-cyrillic.woff2',
    'fonts/RedHatDisplay-700-latin.woff2',
    'fonts/RedHatDisplay-800-latin.woff2',
    'fonts/RedHatDisplay-900-latin.woff2',
    'vendor/pdfjs/pdf.min.mjs',
    'vendor/pdfjs/pdf.worker.min.mjs',
];
// --- end generated ---

const PRECACHE = SHELL.concat(BULK);

// The shell has to come from the deploy, not from an HTTP cache that may still
// be holding the previous build's bytes under the same URL.
const fromNetwork = (url) => new Request(url, { cache: 'reload' });

const resolve = (url) => new URL(url, new URL('./', self.location.href)).href;

// Four shipped files already say what the app needs, and they say it because
// the app itself reads them: index.html names the scripts and stylesheets the
// page loads, manifest.webmanifest the icons a launcher will ask for,
// registry/index.json the jurisdictions the picker offers, and
// fonts/carino-fonts.css the faces the stylesheet fetches. Those are the lists
// that have gone out of step with the cache before — a new country, a new
// weight — so the worker reads them back out of the shell it has just fetched
// and precaches whatever the generated lists missed. That is what stops a
// forgotten run of tools/build_sw.py from costing somebody their offline app.
//
// Everything here is parsed, not guessed, and confined to plain relative paths
// inside the scope. It only ever widens what install tries to fetch, and it is
// tried in the failure-tolerant pass: a declaration is somebody's statement
// that a file exists, which is not the same as the file existing, and a country
// listed in registry/index.json with no record shipped must not be able to hold
// the whole app at "not ready" forever.
function declared(cache) {
    const read = (url, extract) => cache.match(url)
        .then((hit) => (hit ? hit.text() : ''))
        .then((text) => (text ? extract(text) : []))
        .catch(() => []);

    return Promise.all([
        read('index.html', (text) => Array.from(
            text.matchAll(/<(?:script|link)\b[^>]*\s(?:src|href)\s*=\s*["']([^"']+)["']/gi),
            (m) => m[1])),
        read('manifest.webmanifest', (text) =>
            (JSON.parse(text).icons || []).map((icon) => icon.src)),
        read('registry/index.json', (text) => (JSON.parse(text).countries || [])
            .filter((country) => country.tier === 1 || country.tier === 2)
            .map((country) => 'registry/' + String(country.iso).toLowerCase() + '.json')),
        read('fonts/carino-fonts.css', (text) =>
            Array.from(text.matchAll(/url\(\s*["']?\.\/([^)"'\s]+)["']?\s*\)/g), (m) => 'fonts/' + m[1])),
    ]).then((lists) => {
        const base = new URL('./', self.location.href).href;
        const seen = new Set(PRECACHE.map(resolve));
        return lists.flat().filter((url) => {
            if (/^[a-z][a-z0-9+.-]*:|^\/\/|[?#]/i.test(url)) return false;
            const href = resolve(url);
            if (!href.startsWith(base) || seen.has(href)) return false;
            seen.add(href);
            return true;
        });
    });
}

// Always this worker's own generation. While a new build is installing both
// caches exist, and a bare caches.match() would be free to answer the running
// page out of the one belonging to code it has never loaded.
const own = caches.open(VERSION);

// Whoever is open is told a new generation is ready and then left alone. The
// page may work this out for itself from the registration's own updatefound
// event, but a worker that finishes installing while the tab is in the
// background, or before the page attached that listener, would otherwise sit
// waiting with nobody aware of it.
const announce = () => self.clients.matchAll({ type: 'window', includeUncontrolled: true })
    .then((clients) => clients.forEach((client) =>
        client.postMessage({ type: 'UPDATE_AVAILABLE', version: VERSION })));

// A first install has nothing to interrupt, so it takes over the moment its
// cache is complete and the app is offline-capable on the visit that installed
// it. An update is the opposite case: somewhere there is a page with a
// half-entered tax number in a field, and no deploy is worth losing it. That
// worker installs, stays waiting, and announces itself; the page decides when
// to take it, by posting SKIP_WAITING once the user has said so.
self.addEventListener('install', (event) => {
    const updating = Boolean(self.registration.active);
    event.waitUntil(
        own.then((cache) =>
            cache.addAll(SHELL.map(fromNetwork))
                .then(() => declared(cache))
                // Awaited rather than fired and forgotten: work left running
                // after install resolves can be killed when the worker idles,
                // and 1.7 MB of pdf.js half-downloaded is the flagship import
                // failing at the counter.
                .then((extra) => Promise.allSettled(
                    BULK.concat(extra).map((url) => cache.add(fromNetwork(url)))))
                // Only now, with a complete cache behind it, is this worker
                // something a page can safely be moved onto.
                .then(() => (updating ? announce() : self.skipWaiting()))
        )
    );
});

// Claiming matters on a first install, where it is what makes the visit that
// registered the worker an offline-capable one. On an update there is nothing
// left to claim: activation only happens here because the page asked for it,
// and taking control fires controllerchange, which is the page's cue to reload
// itself. Old code being fed new registry JSON is how an app that draws
// conclusions about identifiers comes to be confidently wrong, and the reload
// is what prevents it — but it is the page's reload, at a moment the page chose.
//
// Caches this worker did not create are not this worker's to delete.
self.addEventListener('activate', (event) => {
    event.waitUntil(
        self.clients.claim()
            .then(() => caches.keys())
            .then((keys) => Promise.all(keys
                .filter((key) => key !== VERSION && key.startsWith('carino-fiscal-'))
                .map((key) => caches.delete(key))))
    );
});

// Runtime caching is the net for anything the generated list somehow missed, but
// it is deliberately narrow: same-origin, no query string, never a navigation.
// Card data lives in a URL fragment today, which never reaches the network — if
// it ever moves into a query, this must not be the thing that writes a tax
// identity to disk by accident.
function keepable(request, response) {
    if (!response.ok || response.type !== 'basic' || request.mode === 'navigate') return false;
    const url = new URL(request.url);
    return url.origin === self.location.origin && !url.search;
}

self.addEventListener('fetch', (event) => {
    const request = event.request;
    if (request.method !== 'GET') return;
    const navigating = request.mode === 'navigate';

    event.respondWith(own.then((cache) =>
        // A navigation carries whatever the link that produced it carried:
        // ?lang=ja, a tracker parameter, a QR scanner's own addition. Matching
        // those against the shell exactly is how an installed offline app
        // answers a bookmark with the browser's network-error page.
        cache.match(request, navigating ? { ignoreSearch: true } : undefined).then((hit) => {
            if (hit) return hit;
            return fetch(request).then((response) => {
                if (keepable(request, response)) cache.put(request, response.clone());
                return response;
            }).catch(() =>
                // Offline and not in the cache. A navigation still lands on the
                // app; anything else fails as a failure rather than resolving
                // undefined, which respondWith turns into an opaque error.
                navigating
                    ? cache.match('index.html').then((shell) => shell || Response.error())
                    : Response.error()
            );
        })
    ));
});

// Which required URLs are genuinely in the cache. cache.addAll can only report
// that its fetches resolved; this is the only thing that can say the app will
// actually start with the radio off.
function missingFrom(cache, required) {
    return Promise.all(required.map((url) => cache.match(url).then((hit) => (hit ? null : url))))
        .then((results) => results.filter(Boolean));
}

// Everything answered here is read out of the cache, never out of a list that
// says what ought to be in it. A jurisdiction the app offers but whose record
// never landed is the exact case this has to get right: telling someone at a
// counter that their country works offline, and then not having the file, is
// the same class of harm as a green badge on an identifier nobody checked.
function offlineStatus(cache) {
    return Promise.all([cache.keys(), missingFrom(cache, PRECACHE)]).then(([keys, missing]) => {
        const base = new URL('./', self.location.href).href;
        const countries = keys
            .map((request) => request.url)
            .filter((url) => url.startsWith(base))
            .map((url) => /^registry\/([a-z]{2})\.json$/.exec(url.slice(base.length)))
            .filter(Boolean)
            .map((found) => found[1].toUpperCase())
            .sort();
        return {
            type: 'OFFLINE_STATUS',
            version: VERSION,
            ready: missing.length === 0,
            required: PRECACHE.length,
            present: PRECACHE.length - missing.length,
            entries: keys.length,
            missing: missing,
            countries: countries,
        };
    });
}

function reply(event, message) {
    if (event.ports && event.ports[0]) event.ports[0].postMessage(message);
    else if (event.source) event.source.postMessage(message);
}

self.addEventListener('message', (event) => {
    const message = event.data || {};

    // The user has been asked and has agreed to lose nothing by reloading.
    // Activating from here takes the windows this registration controls, which
    // is what raises controllerchange in them.
    if (message.type === 'SKIP_WAITING') {
        self.skipWaiting();
        return;
    }

    if (message.type !== 'OFFLINE_STATUS') return;

    event.waitUntil(own.then((cache) => offlineStatus(cache).then((status) => {
        reply(event, status);
        // install runs once per VERSION, so a font or a pdf.js chunk that
        // failed there is otherwise missing forever. Asking repairs it.
        return status.missing.length
            ? Promise.allSettled(status.missing.map((url) => cache.add(fromNetwork(url))))
            : null;
    })));
});
