#!/usr/bin/env python3
"""Rewrite the precache lists and VERSION in sw.js from what the repo contains.

Offline is the product's premise, so a file that ships but is not precached is
a shipped bug — and that is exactly how the fonts and the vendored pdf.js came
to be missing from a list somebody maintained by hand. The list is therefore
derived, not written: every web asset in the repo is precached because it is
there, and adding a jurisdiction or a font weight needs no second edit.

VERSION is the sha256 of those same bytes rather than a string someone has to
remember to bump. A build with identical content keeps its cache; a build with
one changed byte anywhere gets a new one and re-precaches the lot.

A generator that has to be remembered is a generator that will be forgotten —
sw.js went stale within a day of this file being written. So the same code runs
as a check, and tools/validate.py fails the build on it: a stale VERSION is not
a cosmetic drift, it is a build every existing install ignores.

    python3 tools/build_sw.py            # rewrite the generated block
    python3 tools/build_sw.py --check    # non-zero if it has drifted
"""

import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SW = ROOT / "sw.js"

BEGIN = "// --- begin generated by tools/build_sw.py ---"
END = "// --- end generated ---"

# What a browser can actually be asked to load. Licences, the README and the
# tooling are shipped by git, not by the app, and have no business in a cache
# the user pays for in disk.
SHIPPED = {".html", ".js", ".mjs", ".css", ".json", ".webmanifest", ".webp", ".png", ".svg", ".woff2"}

SKIP_DIRS = {".git", "tools"}

# A worker caching its own script is how a bad deploy becomes permanent.
# registry/fixtures.json is the gate's own reference data — it is read by
# tools/validate.py under node and never by the app, and it is the largest
# thing in registry/, so a phone would be storing it for nothing.
SKIP_FILES = {"sw.js", "registry/fixtures.json"}


def is_bulk(rel: str) -> bool:
    """Large or individually survivable, so it cannot be allowed to fail install.

    addAll is all-or-nothing. 1.7 MB of pdf.js on a dropping connection, or one
    font weight pruned out of fonts/ without the CSS being regenerated, must not
    be able to leave the user with no offline app at all.
    """
    return rel.startswith("vendor/pdfjs/") or (rel.startswith("fonts/") and rel.endswith(".woff2"))


def render(name: str, urls: list[str]) -> str:
    body = "".join(f"    '{u}',\n" for u in urls)
    return f"const {name} = [\n{body}];\n"


def shipped_assets() -> list[str]:
    assets = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT).as_posix()
        if set(rel.split("/")[:-1]) & SKIP_DIRS or rel in SKIP_FILES:
            continue
        if path.suffix in SHIPPED:
            assets.append(rel)
    return assets


def generate() -> tuple[str, list[str], list[str], str]:
    assets = shipped_assets()

    digest = hashlib.sha256()
    for rel in assets:
        digest.update(rel.encode("utf-8"))
        digest.update((ROOT / rel).read_bytes())
    version = "carino-fiscal-" + digest.hexdigest()[:12]

    # './' and 'index.html' are two distinct cache keys for the same bytes, and
    # a navigation to the bare origin only matches the first.
    shell = ["./"] + [r for r in assets if not is_bulk(r)]
    bulk = [r for r in assets if is_bulk(r)]

    block = (
        f"const VERSION = '{version}';\n\n"
        "// Everything the app cannot start without, fetched all-or-nothing: a\n"
        "// half-installed shell is worse than no shell, because it looks like one.\n"
        f"{render('SHELL', shell)}\n"
        "// Cached in a second, failure-tolerant pass, and still required before the\n"
        "// app will call itself offline ready.\n"
        f"{render('BULK', bulk)}"
    )
    return version, shell, bulk, block


def current_block(src: str) -> str | None:
    found = re.search(re.escape(BEGIN) + r"\n(.*?)" + re.escape(END), src, flags=re.S)
    return found.group(1) if found else None


def check(src: str, version: str, shell: list[str], bulk: list[str], block: str) -> int:
    """Report the drift in the terms that matter, not as a diff of the file."""
    have = current_block(src)
    if have is None:
        print("sw.js has no generated block — restore the markers and run tools/build_sw.py")
        return 1
    if have == block:
        return 0

    listed = set(re.findall(r"^    '(.+)',$", have, flags=re.M))
    wanted = set(shell) | set(bulk)
    for rel in sorted(wanted - listed):
        print(f"{rel} ships but sw.js does not precache it — offline, the app will not have it")
    for rel in sorted(listed - wanted):
        print(f"sw.js precaches {rel}, which is not in the repo — install fails on it")
    if not re.search(rf"const VERSION = '{re.escape(version)}';", have):
        print(f"sw.js VERSION is not the hash of what ships — every existing install "
              f"will keep the cache it already has and never see this build")
    print("run tools/build_sw.py")
    return 1


def main(argv: list[str]) -> int:
    if not SW.exists():
        print(f"missing {SW}")
        return 1

    version, shell, bulk, block = generate()
    src = SW.read_text(encoding="utf-8")

    if "--check" in argv:
        return check(src, version, shell, bulk, block)

    if BEGIN not in src or END not in src:
        print(f"{SW.name} has no generated block — restore the markers before running this")
        return 1

    out = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        BEGIN + "\n" + block + END,
        src,
        flags=re.S,
    )
    if out != src:
        SW.write_text(out, encoding="utf-8")

    print(f"wrote sw.js — {version}, {len(shell)} shell + {len(bulk)} bulk entries"
          f"{'' if out != src else ' (unchanged)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
